# Generated by Django 4.2.2 on 2023-07-04 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StdClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='0802', max_length=20)),
                ('address', models.CharField(default='Default address', max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(default='codetrybe@codetrybe.com', max_length=50)),
                ('gender', models.CharField(default='NULL', max_length=10)),
                ('std_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='panel.stdclass')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+234-', max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(default='Default address', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='Teacher',
            field=models.ManyToManyField(related_name='subject_taught', to='panel.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, limit_choices_to={'name__lte': 8}, related_name='students', to='panel.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stdclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.teacher'),
        ),
        migrations.AddField(
            model_name='stdclass',
            name='subject',
            field=models.ManyToManyField(related_name='classes', to='panel.subject'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='0802', max_length=20)),
                ('address', models.CharField(default='Default address', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
