# Generated by Django 4.2.1 on 2023-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_student_email_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='male', max_length=40),
        ),
    ]
