# Generated by Django 4.2.1 on 2023-07-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_admin_role_student_role_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='term',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
