# Generated by Django 4.2.1 on 2023-07-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_session_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='term',
            new_name='Term',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='Year',
        ),
    ]
