# Generated by Django 4.2.1 on 2023-07-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_rename_term_session_term_rename_name_session_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
    ]
