# Generated by Django 4.2.2 on 2023-07-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_subject_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
